# NumPy

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,4]

In [3]:
type(l)

list

In [4]:
np.array(l)

array([1, 2, 3, 4, 4])

In [6]:
a = np.array(l)

In [7]:
type(a) # n dimensional array

numpy.ndarray

In [8]:
a1 = np.array([1,2,3,4],[3,4,5])

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [9]:
a1 = np.array([[1,2,3,4],[3,4,5,6]]) #list inside list # 2 nested lists

In [11]:
a1

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [14]:
a2 = np.array([[[1,2,3,4],[3,4,5,6]]]) #3 nested lists

In [15]:
a2

array([[[1, 2, 3, 4],
        [3, 4, 5, 6]]])

In [19]:
a.ndim 

1

In [20]:
a1.ndim

2

In [21]:
a2.ndim

3

In [23]:
a3 = np.array([[[1,2,3,4],[3,4,5,6]],[[1,2,3,4],[3,4,5,6]],[[1,2,3,4],[3,4,5,6]]])

In [24]:
a3 # internal arrays are 2-D, (0th array)

array([[[1, 2, 3, 4],
        [3, 4, 5, 6]],

       [[1, 2, 3, 4],
        [3, 4, 5, 6]],

       [[1, 2, 3, 4],
        [3, 4, 5, 6]]])

In [25]:
a3.ndim

3

In [28]:
# asarray
l = [1,2,3,4]

In [29]:
np.asarray(l) # 1-D

array([1, 2, 3, 4])

In [30]:
type(np.asarray(l))

numpy.ndarray

In [31]:
np.matrix(l) # 2-D passing same list results in 2-D

matrix([[1, 2, 3, 4]])

In [32]:
a= np.asarray(l) # 1-D

In [34]:
a

array([1, 2, 3, 4])

In [35]:
m =np.matrix(l) # 2-D

In [36]:
m

matrix([[1, 2, 3, 4]])

In [37]:
type(m)

numpy.matrix

In [39]:
np.asanyarray(a) # converts to matrix if its any array

array([1, 2, 3, 4])

In [40]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

# shallow copy

In [41]:
a

array([1, 2, 3, 4])

In [42]:
a1 = a

In [43]:
a1

array([1, 2, 3, 4])

In [48]:
a

array([1, 2, 3, 4])

In [49]:
a[0]

1

In [50]:
a[0] = 10 # value assignment

In [51]:
a # list is mutable

array([10,  2,  3,  4])

In [52]:
a1 # changes reflected in a1 from a

array([10,  2,  3,  4])

In [53]:
a1[3] = 50 

In [54]:
a1

array([10,  2,  3, 50])

In [55]:
a # changes reflected in a from a1

array([10,  2,  3, 50])

# deepcopy 

In [56]:
a2 = np.copy(a) #deepcopy any changes in a2 does not in a

In [57]:
a2

array([10,  2,  3, 50])

In [58]:
a2[2] = 30

In [59]:
a2 #changes in a2 from a

array([10,  2, 30, 50])

In [61]:
a # changes not reflected in a from a2  # deepcopy 

array([10,  2,  3, 50])

# fromfunction()


In [62]:
# used to generate data

In [46]:
np.fromfunction(lambda i,j : i==j, (3,4)) #  3 row, 4 column # cannot generate 3-D array

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [63]:
np.random.rand(2,3) # 2 rows , 3 columns

array([[0.12528714, 0.09733216, 0.80060512],
       [0.35303475, 0.03551293, 0.47517974]])

In [64]:
np.random.rand(2,3,2) # first 2--> 2matrix and 3*2 matrix are generated

array([[[0.52495809, 0.03432702],
        [0.60700265, 0.65168782],
        [0.85788338, 0.23538262]],

       [[0.5753915 , 0.50812159],
        [0.4004783 , 0.85845425],
        [0.29914129, 0.84785242]]])

In [65]:
np.random.rand(2,3,2,2) 

array([[[[0.99181997, 0.21573334],
         [0.46912875, 0.16275078]],

        [[0.09712313, 0.10978397],
         [0.6302353 , 0.86349017]],

        [[0.36637738, 0.8208422 ],
         [0.56730855, 0.29466029]]],


       [[[0.05205804, 0.15918681],
         [0.43325145, 0.21977055]],

        [[0.34474188, 0.68389443],
         [0.59204918, 0.43746661]],

        [[0.30787769, 0.83069417],
         [0.73719744, 0.72901494]]]])

In [66]:
np.random.rand(2,4,4)

array([[[0.72550779, 0.73442216, 0.44409445, 0.21160514],
        [0.62271051, 0.04519424, 0.52267274, 0.48595807],
        [0.15239558, 0.74902238, 0.99947686, 0.63055145],
        [0.4747836 , 0.5198219 , 0.93034029, 0.34712505]],

       [[0.77835865, 0.14712866, 0.93678301, 0.71413897],
        [0.86318528, 0.30892349, 0.35481538, 0.01631861],
        [0.44202853, 0.48620971, 0.96542511, 0.9163935 ],
        [0.70399679, 0.0834494 , 0.07115918, 0.42609851]]])

In [67]:
np.random.rand(3,4,4)

array([[[0.40189411, 0.70447334, 0.80154922, 0.97188179],
        [0.07550354, 0.47655929, 0.78503539, 0.5930458 ],
        [0.21937505, 0.54170701, 0.70366088, 0.21355246],
        [0.23327097, 0.71563215, 0.33823836, 0.90693753]],

       [[0.11180515, 0.16889834, 0.05298594, 0.33334698],
        [0.41608084, 0.88260523, 0.25018765, 0.56498021],
        [0.00952765, 0.20565598, 0.32704305, 0.63767426],
        [0.22381642, 0.89199   , 0.06765567, 0.26630786]],

       [[0.49358398, 0.15997759, 0.36222176, 0.63846402],
        [0.610894  , 0.22327274, 0.02963464, 0.41730861],
        [0.30658774, 0.09463374, 0.31232732, 0.36165988],
        [0.41139179, 0.4444127 , 0.40236098, 0.61492502]]])

In [52]:
np.random.randn(2,4,4) # mean = 0 , sd =1 in n is std.normal distribution

array([[[-0.44341275,  0.81536613, -0.33070926, -1.55224805],
        [ 0.55671407,  0.71525471, -1.27613772,  0.18772255],
        [-0.22572983,  1.26641313, -1.59764754, -0.64513557],
        [-1.3422909 , -0.12944677,  0.38510887,  0.98467723]],

       [[-0.4934719 ,  0.1326992 , -0.58314106,  0.60978357],
        [-0.97910511, -0.84010323,  0.51260143,  0.01793407],
        [ 1.6805952 , -2.12284732,  1.18043746, -2.11128633],
        [ 0.01314997, -1.34748458, -0.11783158,  2.01753803]]])

In [68]:
np.random.randint(2,4,4) # generates data in integer

array([2, 3, 2, 2])

In [70]:
np.random.randint(0,10,[4,4])

array([[4, 4, 4, 4],
       [6, 5, 9, 6],
       [4, 8, 5, 2],
       [8, 9, 3, 5]])

In [72]:
np.random.randint(0,10,(4,4))

array([[6, 8, 8, 9],
       [3, 9, 2, 3],
       [6, 9, 9, 6],
       [5, 2, 9, 7]])

In [73]:
np.random.randint(0,10,[4,4,2])

array([[[0, 8],
        [3, 2],
        [6, 8],
        [6, 4]],

       [[5, 0],
        [4, 6],
        [0, 2],
        [6, 4]],

       [[7, 9],
        [0, 4],
        [0, 0],
        [0, 5]],

       [[6, 9],
        [6, 6],
        [2, 3],
        [4, 4]]])

In [74]:
d = np.random.randn(2,4,4) 

In [75]:
import pandas as pd

In [76]:
pd.DataFrame(d)

ValueError: Must pass 2-d input. shape=(2, 4, 4)

In [78]:
d = np.random.randn(3,4) 

In [79]:
d

array([[ 0.60192084,  0.90422105, -1.05275156,  0.49985412],
       [ 0.70199648, -0.71855892,  0.49309118, -0.28490285],
       [ 0.41313431, -0.03225043,  0.55262926, -0.55717391]])

In [80]:
pd.DataFrame(d)

0         1         2         3
0  0.601921  0.904221 -1.052752  0.499854
1  0.701996 -0.718559  0.493091 -0.284903
2  0.413134 -0.032250  0.552629 -0.557174

In [81]:
d1 = np.random.randint(0,10,[4,4,2])

In [82]:
pd.DataFrame(d1)

ValueError: Must pass 2-d input. shape=(4, 4, 2)

In [83]:
d1

array([[[5, 9],
        [9, 2],
        [3, 6],
        [8, 5]],

       [[3, 3],
        [2, 7],
        [7, 5],
        [7, 0]],

       [[0, 3],
        [5, 1],
        [3, 9],
        [9, 7]],

       [[6, 3],
        [7, 2],
        [4, 6],
        [6, 4]]])

In [87]:
d1.reshape(2)

ValueError: cannot reshape array of size 32 into shape (2,)

In [88]:
d1.reshape(16,2) # 4*4*2 == 32 and 16*2 ==32

array([[5, 9],
       [9, 2],
       [3, 6],
       [8, 5],
       [3, 3],
       [2, 7],
       [7, 5],
       [7, 0],
       [0, 3],
       [5, 1],
       [3, 9],
       [9, 7],
       [6, 3],
       [7, 2],
       [4, 6],
       [6, 4]])

In [89]:
d1.reshape(16,-1) # negative value is considered as multiplication

array([[5, 9],
       [9, 2],
       [3, 6],
       [8, 5],
       [3, 3],
       [2, 7],
       [7, 5],
       [7, 0],
       [0, 3],
       [5, 1],
       [3, 9],
       [9, 7],
       [6, 3],
       [7, 2],
       [4, 6],
       [6, 4]])

In [90]:
pd.DataFrame(d1.reshape(16,-1)) 

0  1
0   5  9
1   9  2
2   3  6
3   8  5
4   3  3
5   2  7
6   7  5
7   7  0
8   0  3
9   5  1
10  3  9
11  9  7
12  6  3
13  7  2
14  4  6
15  6  4